//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dtb_WSQLBSEntities : DbContext
    {
        public dtb_WSQLBSEntities()
            : base("name=dtb_WSQLBSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_ChiTietGioHang> tbl_ChiTietGioHang { get; set; }
        public virtual DbSet<tbl_ChiTietSach> tbl_ChiTietSach { get; set; }
        public virtual DbSet<tbl_ChiTietTaiKhoan> tbl_ChiTietTaiKhoan { get; set; }
        public virtual DbSet<tbl_GioHang> tbl_GioHang { get; set; }
        public virtual DbSet<tbl_KhachHang> tbl_KhachHang { get; set; }
        public virtual DbSet<tbl_NhanVien> tbl_NhanVien { get; set; }
        public virtual DbSet<tbl_NhaXuatBan> tbl_NhaXuatBan { get; set; }
        public virtual DbSet<tbl_Sach> tbl_Sach { get; set; }
        public virtual DbSet<tbl_TacGia> tbl_TacGia { get; set; }
        public virtual DbSet<tbl_TacPham> tbl_TacPham { get; set; }
        public virtual DbSet<tbl_TaiKhoan> tbl_TaiKhoan { get; set; }
        public virtual DbSet<tbl_TheLoai> tbl_TheLoai { get; set; }
    }
}
