//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietSach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MoTa { get; set; }
        public string AnhBia { get; set; }
        public Nullable<int> GiaBan { get; set; }
    
        public virtual tbl_Sach tbl_Sach { get; set; }
    }
}
