//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_GioHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_GioHang()
        {
            this.tbl_ChiTietGioHang = new HashSet<tbl_ChiTietGioHang>();
        }
    
        public int SoThuTu { get; set; }
        public string MaGioHang { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TongSoLuong { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiaoDuKien { get; set; }
        public string TrangThai { get; set; }
        public string MaKhachHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChiTietGioHang> tbl_ChiTietGioHang { get; set; }
        public virtual tbl_KhachHang tbl_KhachHang { get; set; }
    }
}
