//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Sach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Sach()
        {
            this.tbl_ChiTietGioHang = new HashSet<tbl_ChiTietGioHang>();
            this.tbl_TacPham = new HashSet<tbl_TacPham>();
        }
    
        public int SoThuTu { get; set; }
        public string MaSach { get; set; }
        public string MaNhaXuatBan { get; set; }
        public string MaTacGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ChiTietGioHang> tbl_ChiTietGioHang { get; set; }
        public virtual tbl_ChiTietSach tbl_ChiTietSach { get; set; }
        public virtual tbl_NhaXuatBan tbl_NhaXuatBan { get; set; }
        public virtual tbl_TacGia tbl_TacGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TacPham> tbl_TacPham { get; set; }
    }
}
