//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ChiTietTaiKhoan
    {
        public string TenDangNhap { get; set; }
        public string TenTaiKhoan { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string SoDienThoai { get; set; }
        public string Email { get; set; }
        public string NganHang { get; set; }
        public string TaiKhoan { get; set; }
    
        public virtual tbl_TaiKhoan tbl_TaiKhoan { get; set; }
    }
}
