//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_WebsiteBanSach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_NhanVien
    {
        public int SoThuTu { get; set; }
        public string MaNhanVien { get; set; }
        public string TenDangNhap { get; set; }
    
        public virtual tbl_TaiKhoan tbl_TaiKhoan { get; set; }
    }
}
